name: avdbs
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/app-icon.png'

flutter:
  uses-material-design: true
